### PR TITLE
added /fly :D

### PR DESCRIPTION
**Pull request by whoopsiepoopsie**

### CODE REVIEW

**Comment by dktapps** [comment]
This is an unnecessary cosmetic change.

**Comment by whoopsiepoopsie** [comment]
Why don't you add the thing in Main.php anyway? @dktapps

**Comment by dktapps** [comment]
It's unnecessary. My time is better spent doing other things.

**Comment by whoopsiepoopsie** [comment]
It wasn't cosmetic. It also wasn't unnecessary. Dickhead. @dktapps

**Comment by dktapps** [comment]
lmao, real mature of you to come back after 7 years

**Pull request closed without merging**
